### PR TITLE
Fix typos of "compare".

### LINKED ISSUE #143: Minor typo on "Comapre" Snapshots
It's a minor typo, but it's not just the presentation text...it's all the way into the code and even the file names.  I'll submit a PR if you are ok with me changing it in the code as well...

See https://github.com/code-mancers/rbkit-client/search?utf8=%E2%9C%93&q=Comapre

### PR DESCRIPTION
**Pull request by Fryguy**
Fixes #143

### CODE REVIEW

**Comment by gnufied** [comment]
Some minor typos are left in header files, but other than that it looks good. So if you can fix those, I will be happy to merge.

**Comment by Fryguy** [comment]
Ugh...fixed a type by introducing another typo :flushed:

**Comment by iffyuva** [comment]
are we waiting for more commits in this PR?

**Comment by Fryguy** [comment]
Nope.

**Comment by gnufied** [comment]
@Fryguy thank you contributing to Rbkit app. Let me know if you want help out in the long run or anything.

**Pull request merged**
